#!/bin/sh
clear
echo "Safecast"
echo
echo "Firmware Uploader Mac"
echo
echo
echo

##############################################################################################

DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

##############################################################################################
# Chip definitions
# set ctype to 0 to ask for chip type or to the chip type number
##############################################################################################

ctype=1

chip[1]="atmega328p" ; name[1]="Atmel Mega 328p"



##############################################################################################
# Main Menu definitions
# set menuoption to 0 to display menu or to the menu option number
##############################################################################################

menuoption=1

mainmenu[1]="Program new HEX file"


##############################################################################################
#
# Now select what we are actually going to accomplish with this script
#
##############################################################################################


if [ "$menuoption" = 0 ] ; then
  echo "What would you like to do:"
  echo 
  i=1
  while [ "${mainmenu[$i]}" != "" ]
  do
    echo "$i. ${mainmenu[$i]}" 
    i=`expr $i + 1`
  done
  echo 
  echo "Choose menu option"
  echo 
  read menuoption
  echo
  echo "##############################################################################"
  echo
fi

##############################################################################################
#
# First we are going to select the port to communicate with
#
##############################################################################################

# to display ALL the serial ports remove the two lines below which start "if" & "fi"

echo "The following is a list of the available serial ports:"
echo 

cd $DIR
sport=$(ls /dev/*.*)
i=0
for j in $sport
do
  if [[ "$j" == *tty.usb* ]] ; then
    i=$(( i + 1 ))
    echo "$i. $j"
    port[i]=$j
  fi
done

echo

if [ "$i" = 0 ] ; then
  echo "No relevant port"
  echo 
  exit
fi

if [ "$i" = 1 ] ; then
  inputp=1
  echo "One relevant port so selecting it automatically : ${port[$inputp]}"
  else
  echo "Select which port to write to :"
  echo
  read inputp
fi



##############################################################################################
#
# Now select the HEX file
#
##############################################################################################


  cd $DIR/hex
  files=$(ls *.hex)
  i=0
  for j in $files
  do
    i=$(( i + 1 ))
    file[i]=$j
  done

  if [ "$i" = 1 ] ; then
    input=1
    i=0
    for j in $files
    do
      i=$(( i + 1 ))
      echo "$i. $j"
    done
  fi

##############################################################################################
#
# Now select the chip type
#
##############################################################################################


if [ "$ctype" = 0 ] ; then

  echo "The following is a list of the available chip types:"
  echo 
  i=1
  while [ "${name[$i]}" != "" ]
  do
    echo "$i. ${name[$i]}" 
    i=`expr $i + 1`
  done
  echo 
  echo "Choose chip type"
  echo 
  read ctype
  echo

fi

##############################################################################################
#
# Now do the business
#
##############################################################################################


clear
echo "Safecast firmware Updater"
echo
echo "Writing - ${file[$input]}"
echo "to port - ${port[$inputp]}"
echo "IC      - ${chip[$ctype]}"
echo 
echo


  cd $DIR

  if [ "$menuoption" = "1" ] ; then

    #  Option 1 - Program file to chip
    $DIR/bin/avrdude -C$DIR/bin/avrdude.conf -p${chip[$ctype]} -carduino -P${port[$inputp]} -b57600 -DV -Uflash:w:$DIR/hex/${file[$input]}:i
  fi

exit

##############################################################################################
#
# Information…..
#
##############################################################################################

Valid parts are:

  t10  = ATtiny10        [/usr/local/etc/avrdude.conf:15237]
  t8   = ATtiny9         [/usr/local/etc/avrdude.conf:15197]
  t5   = ATtiny5         [/usr/local/etc/avrdude.conf:15157]
  t4   = ATtiny4         [/usr/local/etc/avrdude.conf:15117]
  ucr2 = 32UC3A0512      [/usr/local/etc/avrdude.conf:15096]
  x128a4 = ATXMEGA128A4    [/usr/local/etc/avrdude.conf:14998]
  x64a4 = ATXMEGA64A4     [/usr/local/etc/avrdude.conf:14901]
  x32a4 = ATXMEGA32A4     [/usr/local/etc/avrdude.conf:14804]
  x16a4 = ATXMEGA16A4     [/usr/local/etc/avrdude.conf:14707]
  x256a3b = ATXMEGA256A3B   [/usr/local/etc/avrdude.conf:14610]
  x256a3 = ATXMEGA256A3    [/usr/local/etc/avrdude.conf:14513]
  x192a3 = ATXMEGA192A3    [/usr/local/etc/avrdude.conf:14416]
  x128a3 = ATXMEGA128A3    [/usr/local/etc/avrdude.conf:14319]
  x64a3 = ATXMEGA64A3     [/usr/local/etc/avrdude.conf:14222]
  x256a1 = ATXMEGA256A1    [/usr/local/etc/avrdude.conf:14125]
  x192a1 = ATXMEGA192A1    [/usr/local/etc/avrdude.conf:14028]
  x128a1d = ATXMEGA128A1REVD [/usr/local/etc/avrdude.conf:13931]
  x128a1 = ATXMEGA128A1    [/usr/local/etc/avrdude.conf:13834]
  x64a1 = ATXMEGA64A1     [/usr/local/etc/avrdude.conf:13737]
  m6450 = ATMEGA6450      [/usr/local/etc/avrdude.conf:13548]
  m3250 = ATMEGA3250      [/usr/local/etc/avrdude.conf:13359]
  m645 = ATMEGA645       [/usr/local/etc/avrdude.conf:13170]
  m325 = ATMEGA325       [/usr/local/etc/avrdude.conf:12981]
  usb82 = AT90USB82       [/usr/local/etc/avrdude.conf:12801]
  usb162 = AT90USB162      [/usr/local/etc/avrdude.conf:12617]
  usb1287 = AT90USB1287     [/usr/local/etc/avrdude.conf:12428]
  usb1286 = AT90USB1286     [/usr/local/etc/avrdude.conf:12239]
  usb647 = AT90USB647      [/usr/local/etc/avrdude.conf:12051]
  usb646 = AT90USB646      [/usr/local/etc/avrdude.conf:11862]
  m32u4 = ATmega32U4      [/usr/local/etc/avrdude.conf:11674]
  t84  = ATtiny84        [/usr/local/etc/avrdude.conf:11491]
  t44  = ATtiny44        [/usr/local/etc/avrdude.conf:11309]
  t24  = ATtiny24        [/usr/local/etc/avrdude.conf:11127]
  m128rfa1 = ATMEGA128RFA1   [/usr/local/etc/avrdude.conf:10939]
  m2561 = ATMEGA2561      [/usr/local/etc/avrdude.conf:10745]
  m2560 = ATMEGA2560      [/usr/local/etc/avrdude.conf:10552]
  m1281 = ATMEGA1281      [/usr/local/etc/avrdude.conf:10364]
  m1280 = ATMEGA1280      [/usr/local/etc/avrdude.conf:10175]
  m640 = ATMEGA640       [/usr/local/etc/avrdude.conf:9987]
  t85  = ATtiny85        [/usr/local/etc/avrdude.conf:9806]
  t45  = ATtiny45        [/usr/local/etc/avrdude.conf:9627]
  t25  = ATtiny25        [/usr/local/etc/avrdude.conf:9447]
  pwm3b = AT90PWM3B       [/usr/local/etc/avrdude.conf:9266]
  pwm2b = AT90PWM2B       [/usr/local/etc/avrdude.conf:9083]
  pwm3 = AT90PWM3        [/usr/local/etc/avrdude.conf:8900]
  pwm2 = AT90PWM2        [/usr/local/etc/avrdude.conf:8716]
  t2313 = ATtiny2313      [/usr/local/etc/avrdude.conf:8529]
  m328p = ATMEGA328P      [/usr/local/etc/avrdude.conf:8341]
  t88  = attiny88        [/usr/local/etc/avrdude.conf:8155]
  m168 = ATMEGA168       [/usr/local/etc/avrdude.conf:7967]
  m88  = ATMEGA88        [/usr/local/etc/avrdude.conf:7781]
  m48  = ATMEGA48        [/usr/local/etc/avrdude.conf:7594]
  t861 = ATTINY861       [/usr/local/etc/avrdude.conf:7406]
  t461 = ATTINY461       [/usr/local/etc/avrdude.conf:7217]
  t261 = ATTINY261       [/usr/local/etc/avrdude.conf:7028]
  t26  = ATTINY26        [/usr/local/etc/avrdude.conf:6871]
  m8535 = ATMEGA8535      [/usr/local/etc/avrdude.conf:6713]
  m8515 = ATMEGA8515      [/usr/local/etc/avrdude.conf:6555]
  m8   = ATMEGA8         [/usr/local/etc/avrdude.conf:6394]
  m161 = ATMEGA161       [/usr/local/etc/avrdude.conf:6254]
  m32  = ATMEGA32        [/usr/local/etc/avrdude.conf:6079]
  m6490 = ATMEGA6490      [/usr/local/etc/avrdude.conf:5886]
  m649 = ATMEGA649       [/usr/local/etc/avrdude.conf:5701]
  m3290p = ATMEGA3290P     [/usr/local/etc/avrdude.conf:5518]
  m3290 = ATMEGA3290      [/usr/local/etc/avrdude.conf:5333]
  m329p = ATMEGA329P      [/usr/local/etc/avrdude.conf:5148]
  m329 = ATMEGA329       [/usr/local/etc/avrdude.conf:4964]
  m169 = ATMEGA169       [/usr/local/etc/avrdude.conf:4784]
  m163 = ATMEGA163       [/usr/local/etc/avrdude.conf:4626]
  m162 = ATMEGA162       [/usr/local/etc/avrdude.conf:4430]
  m1284p = ATMEGA1284P     [/usr/local/etc/avrdude.conf:4240]
  m644p = ATMEGA644P      [/usr/local/etc/avrdude.conf:4048]
  m644 = ATMEGA644       [/usr/local/etc/avrdude.conf:3858]
  m324p = ATMEGA324P      [/usr/local/etc/avrdude.conf:3667]
  m164p = ATMEGA164P      [/usr/local/etc/avrdude.conf:3476]
  m16  = ATMEGA16        [/usr/local/etc/avrdude.conf:3298]
  c32  = AT90CAN32       [/usr/local/etc/avrdude.conf:3107]
  c64  = AT90CAN64       [/usr/local/etc/avrdude.conf:2917]
  c128 = AT90CAN128      [/usr/local/etc/avrdude.conf:2727]
  m128 = ATMEGA128       [/usr/local/etc/avrdude.conf:2549]
  m64  = ATMEGA64        [/usr/local/etc/avrdude.conf:2368]
  m103 = ATMEGA103       [/usr/local/etc/avrdude.conf:2228]
  8535 = AT90S8535       [/usr/local/etc/avrdude.conf:2107]
  8515 = AT90S8515       [/usr/local/etc/avrdude.conf:1993]
  4434 = AT90S4434       [/usr/local/etc/avrdude.conf:1910]
  4433 = AT90S4433       [/usr/local/etc/avrdude.conf:1786]
  2343 = AT90S2343       [/usr/local/etc/avrdude.conf:1662]
  2333 = AT90S2333       [/usr/local/etc/avrdude.conf:1534]
  2313 = AT90S2313       [/usr/local/etc/avrdude.conf:1421]
  4414 = AT90S4414       [/usr/local/etc/avrdude.conf:1308]
  1200 = AT90S1200       [/usr/local/etc/avrdude.conf:1193]
  t15  = ATtiny15        [/usr/local/etc/avrdude.conf:1060]
  t13  = ATtiny13        [/usr/local/etc/avrdude.conf:887]
  t12  = ATtiny12        [/usr/local/etc/avrdude.conf:754]
  t11  = ATtiny11        [/usr/local/etc/avrdude.conf:690]


